<a href="https://colab.research.google.com/github/VitoriaLeticiaa/IA-E-IOT/blob/main/tratamento_PI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import pandas as pd

In [113]:
import seaborn as se

In [114]:
import statistics as st

In [115]:
agendamento = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/agendamento2.csv")

In [116]:
agendamento.head()

,Nome,E-mail,Telefone,Curso,Módulo,N° Computador,Data,Mês,Ano,Hora
0,Vinícius,vinicius23@email.com,81987123409,Administração,3,17.0,17,Março,2024,07:05
1,Patrícia,patricia48@email.com,81985432167,Logística,2,3.0,3,Julho,2025,07:20
2,Lucas,lucas05@email.com,81984769012,Redes de Computadores,3,28.0,28,Janeiro,2024,07:15
3,Bianca,bianca67@email.com,81986547321,Administração,1,12.0,12,Setembro,2024,07:40
4,Thiago,thiago12@email.com,81988901287,Logística,1,41.0,31,Dezembro,2025,08:00

In [117]:
agendamento.isnull().sum()

Nome             0
E-mail           0
Telefone         0
Curso            0
Módulo           0
N° Computador    3
Data             0
Mês              0
Ano              0
Hora             0
dtype: int64

In [118]:
agendamento['N° Computador'].describe()

count    98.000000
mean     19.612245
std      12.174532
min       1.000000
25%       9.000000
50%      18.500000
75%      30.000000
max      42.000000
Name: N° Computador, dtype: float64

In [119]:
mediana = st.median(agendamento['N° Computador'])
mediana

19.0

In [120]:
agendamento['N° Computador'].fillna(mediana, inplace=True)

<ipython-input-120-4004687940>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  agendamento['N° Computador'].fillna(mediana, inplace=True)

In [121]:
agendamento.isnull().sum()

Nome             0
E-mail           0
Telefone         0
Curso            0
Módulo           0
N° Computador    0
Data             0
Mês              0
Ano              0
Hora             0
dtype: int64

In [122]:
agendamento.loc[agendamento.duplicated(['Telefone'], keep=False)]

,Nome,E-mail,Telefone,Curso,Módulo,N° Computador,Data,Mês,Ano,Hora
10,Eduarda,eduarda29@email.com,81985678901,Logística,3,40.0,14,Maio,2025,09:40
100,Eduarda,eduarda29@email.com,81985678901,Logística,3,40.0,14,Maio,2025,09:40

In [123]:
agendamento.drop_duplicates(subset='Telefone', keep='first', inplace=True)

In [124]:
agendamento.loc[agendamento.duplicated(['Telefone'], keep=False)]

Empty DataFrame
Columns: [Nome, E-mail, Telefone, Curso, Módulo, N° Computador, Data, Mês, Ano, Hora]
Index: []

In [125]:
Módulo = agendamento.groupby(['Módulo']).size()
Módulo

Módulo
1       28
2       33
3       38
três     1
dtype: int64

In [126]:
agendamento.loc[agendamento['Módulo'].isin(['três']), 'Módulo'] = '3'

Módulo = agendamento.groupby(['Módulo']).size()
Módulo

Módulo
1    28
2    33
3    39
dtype: int64

In [127]:
Curso = agendamento.groupby(['Curso']).size()
Curso

Curso
Administração            39
Logística                30
Redes de Computadores    31
dtype: int64

In [128]:
agendamento.loc[agendamento['Curso'].isin(['Medicina', 'Engenharia Civil', '1495']), 'Curso'] = 'Administração'

Curso = agendamento.groupby(['Curso']).size()
Curso

Curso
Administração            39
Logística                30
Redes de Computadores    31
dtype: int64

In [129]:
agendamento.shape

(100, 10)

In [130]:
agendamento.head()

,Nome,E-mail,Telefone,Curso,Módulo,N° Computador,Data,Mês,Ano,Hora
0,Vinícius,vinicius23@email.com,81987123409,Administração,3,17.0,17,Março,2024,07:05
1,Patrícia,patricia48@email.com,81985432167,Logística,2,3.0,3,Julho,2025,07:20
2,Lucas,lucas05@email.com,81984769012,Redes de Computadores,3,28.0,28,Janeiro,2024,07:15
3,Bianca,bianca67@email.com,81986547321,Administração,1,12.0,12,Setembro,2024,07:40
4,Thiago,thiago12@email.com,81988901287,Logística,1,41.0,31,Dezembro,2025,08:00

In [132]:
agendamento.to_csv('/content/drive/MyDrive/Colab Notebooks/agendamento3.csv', index=False)